; GreenSense ESP32 firmware
; Sends sensor readings to the Next.js API: /api/iot/readings

[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200

; Define estos puertos solo si quieres fijarlos.
; upload_port = COM8
; monitor_port = COM8

build_flags =
  -DCORE_DEBUG_LEVEL=0

lib_deps =
  adafruit/DHT sensor library @ ^1.4.6
  adafruit/Adafruit Unified Sensor @ ^1.1.15
